### ISSUE TITLE
Readme Error (SSH Port)

### ISSUE THREAD

**Issue by srounet** [kartoza/docker-tilemill#2]
In `run.sh` you bind sshd to 20007 `-p 20007:22`

In `Readme.md` you say `docker run --name=tilemill -p 1100:22 -p 20008:20008 -p 20009:20009 -d -t kartoza/tilemill`

And finally, also in `Readme.md` you say `ssh root@localhost -p 1000`

The only righ thing here is the first one, sshd is bound to 20007.
Can you fix the documentation?

**Comment by timlinux** [comment]
Hi

I think it should read 1100 since that is bound to ssh on port 22. Thanks for your note - I updated the readme. I will probably remove ssh from the image in the future since it is consider not best practice to run ssh in docker.

Please close this ticket if everything is resolved for you.

Regards

Tim
